hasker/hasker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("question.urls")),
    path("user/", include("user.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

hasker/question/urls.py
from django.urls import path

from . import views

app_name = "question"

urlpatterns = [
    path("", views.Questions.as_view(), name="index"),
    path("latest/", views.LatestQuestions.as_view(), name="latest"),
    path("top/", views.TopQuestions.as_view(), name="top"),
    path("search/", views.SearchQuestions.as_view(), name="search"),
    path("tag/<tag>", views.TagQuestions.as_view(), name="tag"),
    path("details/<int:question_id>/", views.details, name="details"),
    path("edit/<int:question_id>/", views.EditQuestion.as_view(), name="edit"),
    path("ask/", views.AskQuestion.as_view(), name="ask"),
    path("answer/<int:question_id>/", views.AnswerQuestion.as_view(), name="answer"),
]

hasker/user/urls.py
from django.conf import settings
from django.urls import include, path
from user.views import (LoginView, LogOutView, PasswordChangeView,
                        SettingsView, SignUpView)

app_name = "site_auth"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogOutView.as_view(), name="logout"),
    path("profile/", SettingsView.as_view(), name="profile"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("password/", PasswordChangeView.as_view(), name="password_change"),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

hasker/question/models.py
from typing import List

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from user.models import User


class Question(models.Model):
    subject = models.CharField(max_length=255, null=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    tag = models.ManyToManyField("Tag", related_name="tags")
    votes = models.IntegerField(default=0, blank=True)
    answers = models.IntegerField(default=0, blank=True)

    def __str__(self):
        (self.subject,)
        (self.author,)
        (self.description,)
        (self.created_date,)
        (self.votes,)
        (self.answers,)
        (", ".join(t.name for t in self.tag.all()),)
        return self.subject

    @classmethod
    def trending(cls, count):
        return cls.objects.filter(votes__gt=0).order_by("-votes")[:count]

    @classmethod
    def get_question(cls, pk):
        if pk:
            obj = get_object_or_404(cls, pk=pk)
            return obj
        else:
            raise Http404

    def add_tags(self, tags):
        for t in tags:
            try:
                tag = Tag.objects.get(name=t)
            except ObjectDoesNotExist:
                tag = Tag.objects.create(name=t)
            self.tag.add(tag)


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    text = models.TextField()
    is_correct = models.BooleanField(default=0, blank=True)
    votes = models.IntegerField(default=0, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    added = models.DateTimeField(auto_now_add=True)
    name = models.CharField(blank=False, max_length=settings.QUESTIONS_TAGS_LENGTH)

    def __str__(self):
        return self.name

hasker/question/forms.py
import re

from django import forms
from django.conf import settings

from .models import Answer, Question


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ("text", "question")
        widgets = {"question": forms.HiddenInput()}


class QuestionForm(forms.ModelForm):
    tags = forms.CharField(max_length=512, required=False)

    class Meta:
        model = Question
        fields = ("description", "subject", "tags")

    def clean_tags(self):
        raw_tags = self.cleaned_data["tags"]
        raw_tags, _ = re.subn(r"\s+", " ", raw_tags)

        tags = (tag.strip().lower() for tag in raw_tags.split(","))
        tags = set(filter(bool, tags))

        if len(tags) > settings.QUESTIONS_MAX_TAGS:
            raise forms.ValidationError(
                f"The maximum number of tags is {settings.QUESTIONS_MAX_TAGS}."
            )

        if any(len(tag) > settings.QUESTIONS_TAGS_LENGTH for tag in tags):
            raise forms.ValidationError(
                f"Max tag lenght {settings.QUESTIONS_TAGS_LENGTH} characters."
            )
        return sorted(tags)

hasker/question/views.py
import time

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from django.views.generic.edit import UpdateView

from .forms import AnswerForm, QuestionForm
from .models import Answer, Question


class Trends:
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["trend"] = Question.trending(count=10)
        return context


class Questions(Trends, ListView):
    template_name = "question/question_list.html"
    model = Question
    paginate_by = 20
    context_object_name = "questions"
    queryset = Question.objects.order_by("?").all()


class LatestQuestions(Questions):
    ordering = "-created_date"


class TopQuestions(Questions):
    ordering = "-votes"


class SearchQuestions(Questions):
    ordering = ("-votes", "-created_date")
    query = ""

    def get(self, *args, **kwargs):
        self.query = self.request.GET.get("q", "").strip()

        if not self.query:
            raise Http404("Query should be specified.")

        if "tag:" in self.query:
            *_, tag = self.query.partition(":")
            tag = tag.strip().lower()
            if tag:
                return redirect("question:tag", tag=tag)
        return super().get(*args, **kwargs)

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(
            Q(subject__icontains=self.query) | Q(description__icontains=self.query)
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["query"] = self.query
        return context


class TagQuestions(Questions):
    ordering = ("-votes", "-created_date")

    def get_queryset(self):
        qs = super().get_queryset()
        tag = self.kwargs["tag"].strip().lower()
        qs = qs.filter(tag__name=tag)
        return qs


def details(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    form = QuestionForm(question_id, request.POST)

    try:
        answers = Answer.objects.filter(question=question_id)
    except Answer.DoesNotExist:
        answers = None
    if request.method == "POST":
        if request.POST["vote"]:
            req = request.POST["vote"].split(",")
            if req[0] == "up":
                question.votes += 1
                question.save()
            elif req[0] == "down":
                question.votes -= 1
                question.save()
            elif req[0] == "answer_up":
                answer = get_object_or_404(Answer, pk=req[1])
                answer.votes += 1
                answer.save()
            elif req[0] == "answer_down":
                answer = get_object_or_404(Answer, pk=req[1])
                answer.votes -= 1
                answer.save()
            elif req[0] == "correct":
                answer = get_object_or_404(Answer, pk=req[1])
                answer.is_correct += 1
                answer.save()
            messages.success(request, "Thank you for voting!")
            return redirect("question:details", question_id=question_id)
    else:
        return render(
            request, "question/details.html", {"question": question, "answers": answers}
        )


class AskQuestion(Trends, LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    model = Question
    template_name = "question/ask_question.html"
    success_url = reverse_lazy("question:latest")

    def form_valid(self, form):
        question = form.save(commit=False)
        question.author = self.request.user
        question.save()

        tags = form.cleaned_data["tags"]
        question.add_tags(tags)
        messages.success(self.request, "Your question posted!")
        return HttpResponseRedirect(
            reverse("question:details", kwargs={"question_id": question.id})
        )


class EditQuestion(Trends, LoginRequiredMixin, UpdateView):
    model = Question
    pk_url_kwarg = "question_id"
    template_name = "question/update_question.html"
    fields = ["subject", "description"]

    def form_valid(self, form):
        question = form.save(commit=False)
        question.author = self.request.user
        question.save()
        messages.success(self.request, "Your question changed!")
        return HttpResponseRedirect(
            reverse(
                "question:details", kwargs={"question_id": self.kwargs["question_id"]}
            )
        )


class AnswerQuestion(Trends, LoginRequiredMixin, CreateView):
    form_class = AnswerForm
    model = Answer
    pk_url_kwarg = "question_id"
    context_object_name = "answers"
    question = None
    template_name = "question/answer.html"

    def get_initial(self):
        return {"question": self._get_question().id}

    def _get_question(self):
        if self.question is None:
            pk = self.kwargs.get("question_id", None)
            self.question = Question.get_question(pk)
        return self.question

    def get_context_data(self, **kwargs):
        context = super(AnswerQuestion, self).get_context_data(**kwargs)
        context["question"] = self._get_question()
        return context

    def answered(self, *args):
        question_id = self.kwargs["question_id"]
        question = get_object_or_404(Question, pk=question_id)
        question.answers += 1
        question.save()

    def form_valid(self, form):
        answer = form.save(commit=False)
        answer.author = self.request.user
        self.answered(self)
        answer.save()
        messages.success(self.request, "Your answer posted!")
        return HttpResponseRedirect(
            reverse(
                "question:details", kwargs={"question_id": self.kwargs["question_id"]}
            )
        )

hasker/question/templates/question/details.html
{% extends 'base/base.html' %}

{% block title %}Details{% endblock %}


{% block content %}
    <main role="main" class="container">
        <div class="row">
            <table class="table">
                 <tr>
                    <td>
                        <div class="mb-3" data-url="{% url 'question:details' question_id=question.pk %}" data-target="{{ question.pk }}">
                            <form action="" method="post">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <button type="submit" name="vote" value="up" style="border:none;background:none;">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                                          <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
                                        </svg>
                                    </button>
                                </div>
                            </form>
                                <div class="mb-3">
                                    <div class="container">
                                    <span>{{ question.votes }}</span>
                                     </div>
                                </div>
                            <form action="" method="post">
                                {% csrf_token %}
                                    <div class="mb-3">
                                        <button type="submit" name="vote" value="down"  style="border:none;background:none;">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-down" viewBox="0 0 16 16">
                                          <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-.845.682-1.464 1.448-1.546 1.07-.113 1.564-.415 2.068-.723l.048-.029c.272-.166.578-.349.97-.484C6.931.08 7.395 0 8 0h3.5c.937 0 1.599.478 1.934 1.064.164.287.254.607.254.913 0 .152-.023.312-.077.464.201.262.38.577.488.9.11.33.172.762.004 1.15.069.13.12.268.159.403.077.27.113.567.113.856 0 .289-.036.586-.113.856-.035.12-.08.244-.138.363.394.571.418 1.2.234 1.733-.206.592-.682 1.1-1.2 1.272-.847.283-1.803.276-2.516.211a9.877 9.877 0 0 1-.443-.05 9.364 9.364 0 0 1-.062 4.51c-.138.508-.55.848-1.012.964l-.261.065zM11.5 1H8c-.51 0-.863.068-1.14.163-.281.097-.506.229-.776.393l-.04.025c-.555.338-1.198.73-2.49.868-.333.035-.554.29-.554.55V7c0 .255.226.543.62.65 1.095.3 1.977.997 2.614 1.709.635.71 1.064 1.475 1.238 1.977.243.7.407 1.768.482 2.85.025.362.36.595.667.518l.262-.065c.16-.04.258-.144.288-.255a8.34 8.34 0 0 0-.145-4.726.5.5 0 0 1 .595-.643h.003l.014.004.058.013a8.912 8.912 0 0 0 1.036.157c.663.06 1.457.054 2.11-.163.175-.059.45-.301.57-.651.107-.308.087-.67-.266-1.021L12.793 7l.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315l-.353-.354.353-.354c.047-.047.109-.176.005-.488a2.224 2.224 0 0 0-.505-.804l-.353-.354.353-.354c.006-.005.041-.05.041-.17a.866.866 0 0 0-.121-.415C12.4 1.272 12.063 1 11.5 1z"/>
                                        </svg>
                                        </button>
                                    </div>
                            </form>
                        </div>
                    </td>
                    <td>
                        <div class="mb-3">
                            <p class="form-label">
                                <h2><a href="{% url 'question:details' question_id=question.pk %}">{{ question.subject }}</a></h2>
                            </p>
                            <p class="wrapword">{{ question.description }}</p>
                            <p class="text-sm">Asked by <a href="#"><b>{{ question.author }}</b></a> on {{ question.created_date }}</p>
                           <div class="mb-1">
                               {% for tag in question.tag.all %}
                                   <a class="btn btn-success btn-sm" href="{% url 'question:tag' tag=tag.name %}">{{ tag.name }}</a>
                               {% endfor %}
                           </div>
                          <div class="container">
                              {% if user == question.author %}
                                 <a class='btn btn-primary' href="{% url 'question:edit' question_id=question.pk %}">Edit</a>
                              {% endif %}
                                 <a class='btn btn-primary' href="{% url 'question:answer' question_id=question.pk %}">Answer</a>
                          </div>
                        </div>
                    </td>
                 </tr>
                 {% for answer in answers %}
                 <tr>
                    <td>
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <button type="submit" name="vote" value="answer_up, {{ answer.pk }}" style="border:none;background:none;">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                                      <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
                                    </svg>
                                </button>
                            </div>
                        </form>
                            <div class="mb-3">
                                <div class="container">
                                <span>{{ answer.votes }}</span>
                                 </div>
                            </div>
                        <form action="" method="post">
                            {% csrf_token %}
                                <div class="mb-3">
                                    <button type="submit" name="vote" value="answer_down, {{ answer.pk }}" style="border:none;background:none;">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-down" viewBox="0 0 16 16">
                                      <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-.845.682-1.464 1.448-1.546 1.07-.113 1.564-.415 2.068-.723l.048-.029c.272-.166.578-.349.97-.484C6.931.08 7.395 0 8 0h3.5c.937 0 1.599.478 1.934 1.064.164.287.254.607.254.913 0 .152-.023.312-.077.464.201.262.38.577.488.9.11.33.172.762.004 1.15.069.13.12.268.159.403.077.27.113.567.113.856 0 .289-.036.586-.113.856-.035.12-.08.244-.138.363.394.571.418 1.2.234 1.733-.206.592-.682 1.1-1.2 1.272-.847.283-1.803.276-2.516.211a9.877 9.877 0 0 1-.443-.05 9.364 9.364 0 0 1-.062 4.51c-.138.508-.55.848-1.012.964l-.261.065zM11.5 1H8c-.51 0-.863.068-1.14.163-.281.097-.506.229-.776.393l-.04.025c-.555.338-1.198.73-2.49.868-.333.035-.554.29-.554.55V7c0 .255.226.543.62.65 1.095.3 1.977.997 2.614 1.709.635.71 1.064 1.475 1.238 1.977.243.7.407 1.768.482 2.85.025.362.36.595.667.518l.262-.065c.16-.04.258-.144.288-.255a8.34 8.34 0 0 0-.145-4.726.5.5 0 0 1 .595-.643h.003l.014.004.058.013a8.912 8.912 0 0 0 1.036.157c.663.06 1.457.054 2.11-.163.175-.059.45-.301.57-.651.107-.308.087-.67-.266-1.021L12.793 7l.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315l-.353-.354.353-.354c.047-.047.109-.176.005-.488a2.224 2.224 0 0 0-.505-.804l-.353-.354.353-.354c.006-.005.041-.05.041-.17a.866.866 0 0 0-.121-.415C12.4 1.272 12.063 1 11.5 1z"/>
                                    </svg>
                                    </button>
                                </div>
                        </form>
                        <div class="mb-3">
                            {% if answer.is_correct > 0 %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                                  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                                </svg>
                            {% else %}
                              {% if user == question.author %}
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <button type="submit" name="vote" value="correct, {{ answer.pk }}" style="border:none;background:none;">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
                                          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                          <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
                                        </svg>
                                    </button>
                                </form>
                              {% else %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
                                  <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                  <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
                                </svg>
                              {% endif %}

                            {% endif %}
                        </div>
                    </td>
                     <td>
                        <p class="wrapword">{{ answer.text }}</p>
                     <td>
                 </tr>
                 {% endfor %}
            </table>
        </div>
    </main>


{% endblock %}

hasker/question/templates/question/question_list.html
{% extends 'base/base.html' %}

{% block title %}Questions{% endblock %}

{% block content %}
    <main role="main" class="container">
        <div class="row">
            <table class="table">
                <td width="70%">
                    <div class="">
                                <nav class="nav">
                                    <div class="container">
                                        <ul class="nav justify-content-center">
                                            <li><a class="nav-link" href="{% url 'question:latest' %}">Latest</a></li>
                                            <b class="nav-link">|</b>
                                            <li><a class="nav-link" href="{% url 'question:top' %}">Top</a></li>
                                        </ul>
                                    </div>
                                </nav>

                                {% for question in questions %}
                                    <div >
                                        <h1><a class="fs-3 link-primary  link-offset-2 link-underline-opacity-0" href="{% url 'question:details' question_id=question.pk %}">{{ question.subject }}</a></h1>
                                        <p >{{ question.description|truncatechars:300 }}</p>
                                        <p>Asked {{ question.created_date }}</p>
                                    </div>
                                    <div>
                                        <div>
                                            <div class="mb-1">
                                                {% for tag in question.tag.all %}
                                                <a class="btn btn-success btn-sm" href="{% url 'question:tag' tag=tag.name %}">{{ tag.name }}</a>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <div class="mb-1">
                                            <a class="btn btn-outline-primary btn-sm" href="{% url 'question:details' question_id=question.pk %}">{{ question.answers }} answers</a>
                                            <a class="btn btn-outline-danger btn-sm" href="{% url 'question:details' question_id=question.pk %}">{{ question.votes }} votes</a>
                                        </div>
                                    </div>
                                {% endfor %}
                    </div>
                </td>
                <td width="30%">
                    <div  class="container">
                        {% block sidebar %}
                        {% include "base/content/sidebar.html" %}
                        {% endblock %}
                    </div>
                </td>
            </table>
        </div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-primary btn-sm" href="?page=1">&laquo; first</a>
            <a class="btn btn-outline-primary btn-sm" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
            <a class="btn btn-outline-primary btn-sm" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="btn btn-outline-primary btn-sm" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

    </main>
{% endblock %}

hasker/question/templates/question/update_question.html
{% extends 'base/base.html' %}

{% block title %}Update Question{% endblock %}


{% block content %}
    <main role="main" class="container">
        <div class="row">
            <table class="table">
                <td width="70%">
                    <div class="">
                    <div class="mb-3">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input class="btn btn-primary" type="submit" value="Update">
                    </form>
                    </div>
                   </div>
                </td>
                <td width="30%">
                    <div  class="container">
                        {% block sidebar %}
                        {% include "base/content/sidebar.html" %}
                        {% endblock %}
                    </div>
                </td>
            </table>
        </div>
    </main>
{% endblock %}