hasker/hasker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("question.urls")),
    path("user/", include("user.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

hasker/question/urls.py
from django.urls import path

from . import views

app_name = "question"

urlpatterns = [
    path("", views.Questions.as_view(), name="index"),
    path("latest/", views.LatestQuestions.as_view(), name="latest"),
    path("top/", views.TopQuestions.as_view(), name="top"),
    path("search/", views.SearchQuestions.as_view(), name="search"),
    path("tag/<tag>", views.TagQuestions.as_view(), name="tag"),
    path("details/<int:question_id>/", views.details, name="details"),
    path("edit/<int:question_id>/", views.EditQuestion.as_view(), name="edit"),
    path("ask/", views.AskQuestion.as_view(), name="ask"),
    path("answer/<int:question_id>/", views.AnswerQuestion.as_view(), name="answer"),
]

hasker/user/urls.py
from django.conf import settings
from django.urls import include, path
from user.views import (LoginView, LogOutView, PasswordChangeView,
                        SettingsView, SignUpView)

app_name = "site_auth"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogOutView.as_view(), name="logout"),
    path("profile/", SettingsView.as_view(), name="profile"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("password/", PasswordChangeView.as_view(), name="password_change"),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

hasker/question/models.py
from typing import List

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from user.models import User


class Question(models.Model):
    subject = models.CharField(max_length=255, null=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    tag = models.ManyToManyField("Tag", related_name="tags")
    votes = models.IntegerField(default=0, blank=True)
    answers = models.IntegerField(default=0, blank=True)

    def __str__(self):
        (self.subject,)
        (self.author,)
        (self.description,)
        (self.created_date,)
        (self.votes,)
        (self.answers,)
        (", ".join(t.name for t in self.tag.all()),)
        return self.subject

    @classmethod
    def trending(cls, count):
        return cls.objects.filter(votes__gt=0).order_by("-votes")[:count]

    @classmethod
    def get_question(cls, pk):
        if pk:
            obj = get_object_or_404(cls, pk=pk)
            return obj
        else:
            raise Http404

    def add_tags(self, tags):
        for t in tags:
            try:
                tag = Tag.objects.get(name=t)
            except ObjectDoesNotExist:
                tag = Tag.objects.create(name=t)
            self.tag.add(tag)


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    text = models.TextField()
    is_correct = models.BooleanField(default=0, blank=True)
    votes = models.IntegerField(default=0, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    added = models.DateTimeField(auto_now_add=True)
    name = models.CharField(blank=False, max_length=settings.QUESTIONS_TAGS_LENGTH)

    def __str__(self):
        return self.name

hasker/question/forms.py
import re

from django import forms
from django.conf import settings

from .models import Answer, Question


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ("text", "question")
        widgets = {"question": forms.HiddenInput()}


class QuestionForm(forms.ModelForm):
    tags = forms.CharField(max_length=512, required=False)

    class Meta:
        model = Question
        fields = ("description", "subject", "tags")

    def clean_tags(self):
        raw_tags = self.cleaned_data["tags"]
        raw_tags, _ = re.subn(r"\s+", " ", raw_tags)

        tags = (tag.strip().lower() for tag in raw_tags.split(","))
        tags = set(filter(bool, tags))

        if len(tags) > settings.QUESTIONS_MAX_TAGS:
            raise forms.ValidationError(
                f"The maximum number of tags is {settings.QUESTIONS_MAX_TAGS}."
            )

        if any(len(tag) > settings.QUESTIONS_TAGS_LENGTH for tag in tags):
            raise forms.ValidationError(
                f"Max tag lenght {settings.QUESTIONS_TAGS_LENGTH} characters."
            )
        return sorted(tags)

hasker/question/views.py
import time

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from django.views.generic.edit import UpdateView

from .forms import AnswerForm, QuestionForm
from .models import Answer, Question


class Trends:
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["trend"] = Question.trending(count=10)
        return context


class Questions(Trends, ListView):
    template_name = "question/question_list.html"
    model = Question
    paginate_by = 20
    context_object_name = "questions"
    queryset = Question.objects.order_by("?").all()


class LatestQuestions(Questions):
    ordering = "-created_date"


class TopQuestions(Questions):
    ordering = "-votes"


class SearchQuestions(Questions):
    ordering = ("-votes", "-created_date")
    query = ""

    def get(self, *args, **kwargs):
        self.query = self.request.GET.get("q", "").strip()

        if not self.query:
            raise Http404("Query should be specified.")

        if "tag:" in self.query:
            *_, tag = self.query.partition(":")
            tag = tag.strip().lower()
            if tag:
                return redirect("question:tag", tag=tag)
        return super().get(*args, **kwargs)

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(
            Q(subject__icontains=self.query) | Q(description__icontains=self.query)
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["query"] = self.query
        return context


class TagQuestions(Questions):
    ordering = ("-votes", "-created_date")

    def get_queryset(self):
        qs = super().get_queryset()
        tag = self.kwargs["tag"].strip().lower()
        qs = qs.filter(tag__name=tag)
        return qs


def details(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    form = QuestionForm(question_id, request.POST)

    try:
        answers = Answer.objects.filter(question=question_id)
    except Answer.DoesNotExist:
        answers = None
    if request.method == "POST":
        if request.POST["vote"]:
            req = request.POST["vote"].split(",")
            if req[0] == "up":
                question.votes += 1
                question.save()
            elif req[0] == "down":
                question.votes -= 1
                question.save()
            elif req[0] == "answer_up":
                answer = get_object_or_404(Answer, pk=req[1])
                answer.votes += 1
                answer.save()
            elif req[0] == "answer_down":
                answer = get_object_or_404(Answer, pk=req[1])
                answer.votes -= 1
                answer.save()
            elif req[0] == "correct":
                answer = get_object_or_404(Answer, pk=req[1])
                answer.is_correct += 1
                answer.save()
            messages.success(request, "Thank you for voting!")
            return redirect("question:details", question_id=question_id)
    else:
        return render(
            request, "question/details.html", {"question": question, "answers": answers}
        )


class AskQuestion(Trends, LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    model = Question
    template_name = "question/ask_question.html"
    success_url = reverse_lazy("question:latest")

    def form_valid(self, form):
        question = form.save(commit=False)
        question.author = self.request.user
        question.save()

        tags = form.cleaned_data["tags"]
        question.add_tags(tags)
        messages.success(self.request, "Your question posted!")
        return HttpResponseRedirect(
            reverse("question:details", kwargs={"question_id": question.id})
        )


class EditQuestion(Trends, LoginRequiredMixin, UpdateView):
    model = Question
    pk_url_kwarg = "question_id"
    template_name = "question/update_question.html"
    fields = ["subject", "description"]

    def form_valid(self, form):
        question = form.save(commit=False)
        question.author = self.request.user
        question.save()
        messages.success(self.request, "Your question changed!")
        return HttpResponseRedirect(
            reverse(
                "question:details", kwargs={"question_id": self.kwargs["question_id"]}
            )
        )


class AnswerQuestion(Trends, LoginRequiredMixin, CreateView):
    form_class = AnswerForm
    model = Answer
    pk_url_kwarg = "question_id"
    context_object_name = "answers"
    question = None
    template_name = "question/answer.html"

    def get_initial(self):
        return {"question": self._get_question().id}

    def _get_question(self):
        if self.question is None:
            pk = self.kwargs.get("question_id", None)
            self.question = Question.get_question(pk)
        return self.question

    def get_context_data(self, **kwargs):
        context = super(AnswerQuestion, self).get_context_data(**kwargs)
        context["question"] = self._get_question()
        return context

    def answered(self, *args):
        question_id = self.kwargs["question_id"]
        question = get_object_or_404(Question, pk=question_id)
        question.answers += 1
        question.save()

    def form_valid(self, form):
        answer = form.save(commit=False)
        answer.author = self.request.user
        self.answered(self)
        answer.save()
        messages.success(self.request, "Your answer posted!")
        return HttpResponseRedirect(
            reverse(
                "question:details", kwargs={"question_id": self.kwargs["question_id"]}
            )
        )

hasker/question/templates/base/content/header.html
{% load static %}
  <header class="p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <span class="fs-2">Hasker</span>
      </a>

        <ul class="nav col-12 col-lg-auto mb-2 justify-content-center mb-md-0 p-3">
          <li class="nav-item"><a href="{% url 'question:ask' %}" class="btn btn-primary" aria-current="page">Ask question</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search"  action="{% url 'question:search' %}">
          <input type="search" class="form-control" name="q" placeholder="Search..." aria-label="Search" value="{{ query }}">
        </form>

        {% if request.user.is_authenticated %}
        <div class="dropdown text-end">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{{ request.user.get_thumb_url }}" alt="H" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small">
              <li><a class="dropdown-item" href="{% url 'site_auth:profile' %}">Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'site_auth:logout' %}">Sign out</a></li>
          </ul>
        {% else %}
          <div class="text-end">
            <a class="btn btn-light me-2" href="{% url 'site_auth:login' %}" > Login</a>
            <a href="{% url 'site_auth:signup' %}" class="btn btn-warning">Sign-up</a>
          </div>
        {% endif %}
        </div>
      </div>
    </div>
  </header>

hasker/question/templates/base/content/paginator.html
{% if page_obj.has_other_pages %}
<ul class="pagination pagination-centered">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
    {% endif %}

    {% for i in page_obj.paginator.page_range %}
        <li class="page-item" {% if page_obj.number == i %} class="active" {% endif %}>
            <a class="page-link" href="?page={{i}}">{{i}}</a>
        </li>
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    {% endif %}
</ul>
{% endif %}

hasker/question/templates/base/content/sidebar.html
{% block content %}
<div class="container">
    <h3 align="center">In Trends</h3>
    <hr>
    {% for question in trend %}
    <div class="font-monospace">
        <div>
            <a class="fs-5 link-success  link-offset-2 link-underline-opacity-0" href="{% url 'question:details' question_id=question.pk %}">{{ question.subject }}</a>
        </div>
        <span class="btn btn-light btn-sm">{{ question.votes }} votes</span>
    </div>
    {% endfor %}
</div>
{% endblock %}