hasker/hasker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("question.urls")),
    path("user/", include("user.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

hasker/user/urls.py
from django.conf import settings
from django.urls import include, path
from user.views import (LoginView, LogOutView, PasswordChangeView,
                        SettingsView, SignUpView)

app_name = "site_auth"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogOutView.as_view(), name="logout"),
    path("profile/", SettingsView.as_view(), name="profile"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("password/", PasswordChangeView.as_view(), name="password_change"),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

hasker/user/models.py
import time
from hashlib import md5

from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from django.templatetags.static import static
from PIL import Image


def user_photo_path(instance, filename):
    name, sep, ext = filename.rpartition(".")
    if not sep:
        ext = ".jpg"
    new_filename = md5(str(time.time()).encode("utf-8")).hexdigest()
    return f"{new_filename}.{ext}"


def user_photo_size_validator(photo):
    max_size = 1
    if photo.size > max_size * 1024 * 1024:
        raise ValidationError(f"The maximum file size is {max_size}MB")
    return photo


class User(AbstractUser):
    email = models.EmailField(max_length=254, unique=True)
    username = models.CharField(max_length=50, blank=False, unique=True)
    photo = models.ImageField(
        blank=True,
        upload_to=user_photo_path,
        validators=[user_photo_size_validator],
    )
    thumb = models.ImageField(blank=True, editable=False, upload_to=user_photo_path)

    def save(self, *args, **kwargs):
        if self.photo and self._state.adding:
            self.create_thumbnail()
        super().save(*args, **kwargs)

    def create_thumbnail(self, save=False):
        content = ContentFile(b"")
        with Image.open(self.photo) as img:
            img.thumbnail((150, 150))
            img.convert(mode="RGB").save(content, format="JPEG")

        self.thumb = InMemoryUploadedFile(
            content, None, "temp.jpg", "image/jpeg", len(content), None
        )
        if save:
            self.save(update_fields=["thumb"])

    def get_photo_url(self):
        if self.photo:
            return self.photo.url
        return static("media/user.png")

    def get_thumb_url(self):
        if self.thumb:
            return self.thumb.url
        return self.get_photo_url()

hasker/user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import \
    AuthenticationForm as AuthenticationFormGeneric
from django.contrib.auth.forms import UserChangeForm as UserChangeFormGeneric
from django.contrib.auth.forms import \
    UserCreationForm as UserCreationFormGeneric


class AuthenticationForm(AuthenticationFormGeneric):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field: forms.Field
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"


class UserCreationForm(UserCreationFormGeneric):
    class Meta(UserCreationFormGeneric.Meta):
        model = get_user_model()
        fields = ("username", "email", "photo", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field: forms.Field
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"


class SettingsForm(UserChangeFormGeneric):
    password = None

    class Meta:
        model = get_user_model()
        fields = ("email", "photo")

hasker/user/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.views import LoginView as LoginViewGeneric
from django.contrib.auth.views import LogoutView as LogoutViewGeneric
from django.contrib.auth.views import \
    PasswordChangeView as PasswordChangeViewGeneric
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from user.forms import AuthenticationForm, SettingsForm, UserCreationForm


class PasswordChangeView(PasswordChangeViewGeneric):
    template_name = "user/change_password.html"
    form_class = PasswordChangeForm
    success_url = reverse_lazy("question:index")


class LoginView(LoginViewGeneric):
    template_name = "user/login.html"
    form_class = AuthenticationForm
    next_page = reverse_lazy("site_auth:profile")


class LogOutView(LogoutViewGeneric):
    next_page = reverse_lazy("question:index")


class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = "user/register.html"
    success_url = reverse_lazy("question:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        # user: AbstractUser = self.object
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user: AbstractUser = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class SettingsView(UpdateView):
    form_class = SettingsForm
    success_url = reverse_lazy("site_auth:profile")
    template_name = "user/profile.html"

    def form_valid(self, *args, **kwargs):
        messages.success(self.request, "Your settings have been successfully updated!")
        return super().form_valid(*args, **kwargs)

    def form_invalid(self, *args, **kwargs):
        self.object.refresh_from_db()
        return super().form_invalid(*args, **kwargs)

    def get_object(self, queryset=None):
        return self.request.user

hasker/user/templates/user/change_password.html
{% extends "base/base.html" %}

{% block title %}Change Password{% endblock %}


{% block content %}
<main class="container w-50 m-auto">
        <h3>Change Password:</h3>
  <div class="content w-50">
    <div class="tab-pane fade show active" id="pills-profile" role="tabpanel">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-primary" type="submit" value="Save settings">
    </form>
    </div>
</main>
{% endblock content %}

hasker/user/templates/user/login.html
{% extends 'base/base.html' %}

{% block title %}Login{% endblock %}


{% block content %}
<main class="container w-50 m-auto">
        <h3>Log In</h3>
  <div class="content w-50">
    <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
        <form method="post"">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="next" value="{{ next }}">
        <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
        <a href="{% url 'site_auth:signup' %}" class="btn btn-outline-dark btn-block mb-4">Sign up</a>
        </form>
    </div>
</main>
<!-- Pills content -->
{% endblock %}

</html>>

hasker/user/templates/user/profile.html
{% extends "base/base.html" %}

{% block title %}Profile{% endblock %}


{% block content %}

<main class="container w-50 m-auto">
        <h3> Hasker user </h3>
        <br>
  <div class="content w-50">
        <div class="content w-50">
              <img style="padding: 50px;" src="{{ request.user.get_photo_url }}" width="324" height="324"  alt="Photo"/>
        </div>
    <div class="tab-pane fade show active" id="pills-profile" role="tabpanel">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
        <div class="form-label">
            <div class="container mb-3">
                <input
                    class="form-control {% if form.email.errors %} alert-danger {% endif %}"
                    type="email"
                    name="email"
                    placeholder="Email"
                    required
                    {% if form.email.value != None %}value="{{ form.email.value|stringformat:'s' }}"{% endif %}
                >
            </div>
            {% if form.email.errors %}
            <div class="alert alert-danger">{{ form.email.errors }}</div>
            {% endif %}
        </div>
        <div class="container">
            <div class="input-group mb-3">
                <input class="form-control {% if form.photo.errors %} alert-danger {% endif %}" type="file" placeholder="Select your photo" name="photo" accept="image/*">
            </div>
            {% if form.photo.errors %}
                <div class="alert-danger">{{ form.photo.errors }}</div>
            {% endif %}
        </div>
  <div class="content">
      <a class="btn btn-primary" href="{% url 'site_auth:password_change' %}">Change password</a>
      <input class="btn btn-primary" type="submit" value="Save settings">
  </div>
    </form>
    </div>
</main>


{% endblock content %}

hasker/user/templates/user/register.html
{% extends 'base/base.html' %}

{% block title %}
  Register
{% endblock %}

{% block content %}
<main class="container w-50 m-auto">
        <h3>Registration</h3>
  <div class="content w-50">
    <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-primary" type="submit" value="Register">
    </form>
    </div>
</main>
{% endblock %}